sudo: false

# Don't clone submodules, to save on build time we rely on
# binary p2 repo instead using travis profile
git:
  submodules: false

language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

install:
  - git clone --depth 1 --branch master https://github.com/yamcs/yamcs
  - mvn install -DskipTests -f yamcs/pom.xml
  - sed "s#REPLACE_WITH_LOCAL_P2_REPO#"`pwd`/css/local_p2_repository"#" css/settings_template.xml >css/settings.xml

script:
  - mvn verify -f yamcs-studio-bundles/pom.xml -s css/settings.xml -Pcss-for-yamcs,travis
  - mvn verify -f yamcs-studio-tycho/pom.xml -s css/settings.xml -Pcss-for-yamcs,travis

deploy:
  provider: releases
  api_key:
    secure: ktoD9ri1FuwXwHUj2nUbog/lwo1MY4yW2NjLpdzRlHMLZD3juDpCFF1Mn852C8j11wKnLJR72klbMig7/WmW0yr+r5uKer6tGLMsRexSDyNUSVaDBILro14N5XLCTj/2LCfNB2WZyPVYdg/kjTjLSl1NYQUhFU8jwYW3sUpBFBo=
  file_glob: true
  file:
    - yamcs-studio-tycho/yamcs-studio-repository/target/products/yamcs-studio-*.zip
    - yamcs-studio-tycho/yamcs-studio-repository/target/products/yamcs-studio-*.tar.gz
  skip_cleanup: true
  on:
    tags: true

